version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: clinicadb
      POSTGRES_USER: clinica
      POSTGRES_PASSWORD: clinica123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./backend
    # ports:
    #  - "8080:8080" # Comentado para evitar conflito na VPS. O Dokploy fará o roteamento interno pelo domínio.
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clinicadb
      SPRING_DATASOURCE_USERNAME: clinica
      SPRING_DATASOURCE_PASSWORD: clinica123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080
    # ports:
    #  - "3000:80" # Comentado para evitar conflito na VPS. O Dokploy fará o roteamento interno pelo domínio.
    depends_on:
      - app

volumes:
  pgdata:
